name: cloud9
version: 3.0
vendor: Leo Arias <elopio@ubuntu.com>
summary: A powerful online code editor
description: |
  Cloud9 provides a development environment in the cloud that allows developers
  to get started with coding immediately and collaborate with their peers.
icon: build/ubuntu/icon.png

services:
  server:
    start: bin/cloud9.sh
    descrition: cloud9 IDE

parts:
  cloud9:
    plugin: nodejs
    source: .
  wrapper:
    plugin: copy
    files:
      build/ubuntu/cloud9.sh: bin/cloud9.sh
  c9iderun:
    plugin: nodejs
    source: https://github.com/c9/c9.ide.run.git
    source-type: git
  c9iderunbuild:
    plugin: nodejs
    source: https://github.com/c9/c9.ide.run.build.git
    source-type: git
  pluginscopy:
    after:
      - c9iderun
      - c9iderunbuild
    plugin: copy
    files:
      parts/c9iderun/src: lib/node_modules/c9/plugins/c9.ide.run
      parts/c9iderunbuild/src: lib/node_modules/c9/plugins/c9.ide.run.build
